### ISSUE TITLE
Please update Authelia

### ISSUE THREAD

**Issue by BlackHoleFox** [BenoitAnastay/home-assistant-addons-repository#4]
I know the extension is in dev/experimental access but its a simple enough design that I've been experimenting using it, to much success. If time permits would you be able to update the version of your Authelia container served from the this repo so v38 is available to use?

**Comment by BenoitAnastay** [comment]
I have to update the scaffolding of the configuration files but you can check the edge repository for a more updated version of authelia.

At this time you'll need to update the configuration manually 

https://github.com/BenoitAnastay/home-assistant-addons-repository-edge

**Comment by BlackHoleFox** [comment]
That works perfectly, thanks :). I didn't think to look for an edge repository. It got me unblocked to continue making a configuration file.

**Comment by BlackHoleFox** [comment]
The new 0.1.2 update from today works great, thanks much for the work :)
